---
title: "아파트"
description: |
  공공데이터 포털에서 국토부 아파트매매 실거래 상세 데이터를 다운로드 받습니다. 
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(httr)
```



# 서울시 아파트

공공데이터 포털에서 
[국토교통부 아파트매매 실거래 상세 자료](https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15057511)를 API 호출하여 다운로드 받습니다.

## 서울시 - 1 지역코드 

```{r aptraw-data}
# 0. 환경설정 -----
library(tidyverse)
library(rvest)
library(httr)

# 1. 데이터 받아오기 -----
## 1.1 POST() 함수를 사용하여 개표 결과를 수집합니다.
resp <- POST(
    url = 'http://info.nec.go.kr/electioninfo/electionInfo_report.xhtml',
    encode = 'form', 
    body = list(
       electionId = "0020210407",
       requestURI = "/WEB-INF/jsp/electioninfo/0020210407/vc/vccp08.jsp",
       topMenuId = "VC",
       secondMenuId = "VCCP08",
       menuId = "VCCP08",
       statementId = "VCCP08_#3",
       electionCode = "3",
       cityCode = "1100",
       sggCityCode = "-1",
       townCodeFromSgg = "-1",
       townCode = "1101",
       checkCityCode = "-1",
       x = "17",
       y = "9"
    )
  )

vote_raw <- content(x=resp, as = 'text') %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="table01"]') %>% 
  html_table(fill=TRUE) %>% 
  janitor::clean_names() %>% 
  as_tibble() 

vote_tbl <- vote_raw %>% 
    set_names(c("읍면동명", "투표구명", "선거인수", "투표수", "민주당", "국힘당", glue::glue("후보{1:10}"), "계", "무효", "기권")) %>% 
    select(읍면동명, 투표구명, 선거인수, 투표수, 민주당, 국힘당, 기권) %>% 
    slice(2:n()) %>% 
    mutate(읍면동명 = ifelse(읍면동명 == "", NA, 읍면동명)) %>% 
    mutate(읍면동명 = zoo::na.locf(읍면동명)) %>% 
    filter(투표구명 != "", 
           투표구명 != "소계") %>% 
    mutate_at(c("선거인수", "투표수", "민주당", "국힘당", "기권"), parse_number) %>% 
    mutate(구명 = "종로구") %>% 
    relocate(구명, before = "읍면동명")

vote_tbl
```

## 서울시장 - 종로구 함수

```{r raw-data-function}

get_vote <- function(gu_code) {
    resp <- POST(
        url = 'http://info.nec.go.kr/electioninfo/electionInfo_report.xhtml',
        encode = 'form', 
        body = list(
           electionId = "0020210407",
           requestURI = "/WEB-INF/jsp/electioninfo/0020210407/vc/vccp08.jsp",
           topMenuId = "VC",
           secondMenuId = "VCCP08",
           menuId = "VCCP08",
           statementId = "VCCP08_#3",
           electionCode = "3",
           cityCode = "1100",
           sggCityCode = "-1",
           townCodeFromSgg = "-1",
           townCode = gu_code,
           checkCityCode = "-1",
           x = "17",
           y = "9"
        )
      )
    
    vote_raw <- content(x=resp, as = 'text') %>% 
      read_html() %>% 
      html_node(xpath = '//*[@id="table01"]') %>% 
      html_table(fill=TRUE) %>% 
      janitor::clean_names() %>% 
      as_tibble() 
    
    vote_tbl <- vote_raw %>% 
        set_names(c("읍면동명", "투표구명", "선거인수", "투표수", "민주당", "국힘당", glue::glue("후보{1:10}"), "계", "무효", "기권")) %>% 
        select(읍면동명, 투표구명, 선거인수, 투표수, 민주당, 국힘당, 기권) %>% 
        slice(2:n()) %>% 
        mutate(읍면동명 = ifelse(읍면동명 == "", NA, 읍면동명)) %>% 
        mutate(읍면동명 = zoo::na.locf(읍면동명)) %>% 
        filter(투표구명 != "", 
               투표구명 != "소계") %>% 
        mutate_at(c("선거인수", "투표수", "민주당", "국힘당", "기권"), parse_number) %>% 
        mutate(구코드 = gu_code) %>% 
        relocate(구코드, .before = "읍면동명")
    
    vote_tbl    
}

get_vote("1101")

```


## 서울시장 - 서울시 전체

```{r raw-data-all, eval = TRUE}

# seoul_raw <- map_df(gu_code, get_vote)
# 
# seoul_tbl <- seoul_raw %>% 
#     left_join(gu_name_tbl) %>% 
#     select(-구코드) %>% 
#     relocate(구명, .before = "읍면동명")
# 
# seoul_tbl %>% 
#     write_rds("data/seoul_tbl.rds")

seoul_tbl <- read_rds("data/seoul_tbl.rds")

seoul_tbl %>% 
  reactable::reactable()
```

# 부산시장

## 부산시장 - 중구 

```{r raw-data-pusan}

# 1. 데이터 받아오기 -----
## 1.1 POST() 함수를 사용하여 개표 결과를 수집합니다.
pusan_resp <- POST(
    url = 'http://info.nec.go.kr/electioninfo/electionInfo_report.xhtml',
    encode = 'form', 
    body = list(
       electionId = "0020210407",
       requestURI = "/WEB-INF/jsp/electioninfo/0020210407/vc/vccp08.jsp",
       topMenuId = "VC",
       secondMenuId = "VCCP08",
       menuId = "VCCP08",
       statementId = "VCCP08_#3",
       electionCode = "3",
       cityCode = "2600",
       sggCityCode = "-1",
       townCodeFromSgg = "-1",
       townCode = "2601",
       checkCityCode = "-1",
       x = "17",
       y = "9"
    )
  )

busan_vote_raw <- content(x = pusan_resp, as = 'text') %>% 
  read_html() %>% 
  html_node(xpath = '//*[@id="table01"]') %>% 
  html_table(fill=TRUE) %>% 
  janitor::clean_names() %>% 
  as_tibble() 

busan_vote_tbl <- busan_vote_raw %>% 
    set_names(c("읍면동명", "투표구명", "선거인수", "투표수", "민주당", "국힘당", glue::glue("후보{1:4}"), "계", "무효", "기권")) %>% 
    select(읍면동명, 투표구명, 선거인수, 투표수, 민주당, 국힘당, 기권) %>% 
    slice(2:n()) %>% 
    mutate(읍면동명 = ifelse(읍면동명 == "", NA, 읍면동명)) %>% 
    mutate(읍면동명 = zoo::na.locf(읍면동명)) %>% 
    filter(투표구명 != "", 
           투표구명 != "소계") %>% 
    mutate_at(c("선거인수", "투표수", "민주당", "국힘당", "기권"), parse_number) %>% 
    mutate(구명 = "중구") %>% 
    relocate(구명, before = "읍면동명")

busan_vote_tbl
```

## 부산시장 - 중구 함수

```{r busan-raw-data-function}

get_busan_vote <- function(gu_code) {
    resp <- POST(
        url = 'http://info.nec.go.kr/electioninfo/electionInfo_report.xhtml',
        encode = 'form', 
        body = list(
           electionId = "0020210407",
           requestURI = "/WEB-INF/jsp/electioninfo/0020210407/vc/vccp08.jsp",
           topMenuId = "VC",
           secondMenuId = "VCCP08",
           menuId = "VCCP08",
           statementId = "VCCP08_#3",
           electionCode = "3",
           cityCode = "2600",
           sggCityCode = "-1",
           townCodeFromSgg = "-1",
           townCode = gu_code,
           checkCityCode = "-1",
           x = "17",
           y = "9"
        )
      )
    
    vote_raw <- content(x=resp, as = 'text') %>% 
      read_html() %>% 
      html_node(xpath = '//*[@id="table01"]') %>% 
      html_table(fill=TRUE) %>% 
      janitor::clean_names() %>% 
      as_tibble() 
    
    vote_tbl <- vote_raw %>% 
        set_names(c("읍면동명", "투표구명", "선거인수", "투표수", "민주당", "국힘당", glue::glue("후보{1:4}"), "계", "무효", "기권")) %>% 
        select(읍면동명, 투표구명, 선거인수, 투표수, 민주당, 국힘당, 기권) %>% 
        slice(2:n()) %>% 
        mutate(읍면동명 = ifelse(읍면동명 == "", NA, 읍면동명)) %>% 
        mutate(읍면동명 = zoo::na.locf(읍면동명)) %>% 
        filter(투표구명 != "", 
               투표구명 != "소계") %>% 
        mutate_at(c("선거인수", "투표수", "민주당", "국힘당", "기권"), parse_number) %>% 
        mutate(구코드 = gu_code) %>% 
        relocate(구코드, .before = "읍면동명")
    
    vote_tbl    
}

get_busan_vote("2601")
```


## 부산시장 - 부산시 전체

```{r busan-raw-data-all, eval = TRUE}
# gu_busan_code <- glue::glue("26{str_pad(1:16, width = 2, side='left', pad =0)}")
# gu_name_busan_tbl <- tribble(~"구코드", ~"구명",
#                               "2601", "중구",
#                               "2602", "서구",
#                               "2603", "동구",
#                               "2604", "영도구",
#                               "2605", "부산진구",
#                               "2606", "동래구",
#                               "2607", "남구",
#                               "2608", "북구",
#                               "2609", "해운대구",
#                               "2610", "기장군",
#                               "2611", "사하구",
#                               "2612", "금정구",
#                               "2613", "강서구",
#                               "2614", "연제구",
#                               "2615", "수영구",
#                               "2616", "사상구")
# 
# busan_raw <- map_df(gu_busan_code, get_busan_vote)
# 
# busan_tbl <- busan_raw %>%
#     left_join(gu_name_busan_tbl) %>%
#     select(-구코드) %>%
#     relocate(구명, .before = "읍면동명")
# 
# busan_tbl %>%
#     write_rds("data/busan_tbl.rds")

busan_tbl <- read_rds("data/busan_tbl.rds")

busan_tbl %>% 
  reactable::reactable()
```


